### PR TITLE
Testing-branch

### PR DESCRIPTION
**Pull request by MrPigeontheCoder**
Maybe this will fix all the ISSUES with the images

### CODE REVIEW

**Comment by MrPigeontheCoder** [comment]
ok this should work

**Review by stretch07 — COMMENTED** [review]
hey - i've been trying to get rid of pages to make them headings on one main page so making something like `dialog/alert/confirm.md` `dialog/alert/confirm/README.md` does quite the opposite!
Please see https://github.com/win93-community/windows93-docs/issues/9

In the future try to let me review before merging perhaps 🙃

**Comment by MrPigeontheCoder** [comment]
Sorry about that... 😅🙃

**Comment by MrPigeontheCoder** [comment]
What if we use a Codespace to test stuff? @its-pablo

**Pull request merged**
