### PR TITLE
Image-fixing-branch

### PR DESCRIPTION
**Pull request by MrPigeontheCoder**
fixed a few thingies

### CODE REVIEW

**Review by stretch07 — COMMENTED** [review]
hello!
some of the links are broken - remember /docs is where the documentation is served from, and the base directory is already /docs so there is no need to specify it in the sidebar.

I'm going to look more into the images issue later
Also can we keep the deprecated apis in their respective category but add a trash can icon? I think they will be somewhat more useful that way
let's try to test before pushing breaking changes as well 😅

**Comment by MrPigeontheCoder** [comment]
> 

Ok, but wdym by testing? Deploying on a separate page?

**Comment by stretch07** [comment]
No, i meant testing on your local device before pushing changes
Or using codespaces :)

**Comment by MrPigeontheCoder** [comment]
> No, i meant testing on your local device before pushing changes
> Or using codespaces :)

Ok, got it

**Pull request merged**
